dist: trusty
sudo: required

language: node_js

node_js:
  - 'stable'
  - '9'

addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable

cache:
  directories:
     - ./node_modules

before_install:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - npm i -g npm@5
  
install:
  - npm install

script:
  - npm run lint
  - npm run test
  - npm run build
