[build]
  publish = "dist/"
  command = "yarn build:network --verbose --history"

[context.deploy-preview.environment]
  CURRENT_NETWORK = "dalinet"

[context.branch-deploy.environment]
  CURRENT_NETWORK = "dalinet"

# Dalinet
[context."develop".environment]
  CURRENT_NETWORK = "dalinet"

# Dalinet
[context."dalinet".environment]
  CURRENT_NETWORK = "dalinet"

# Sandbox
[context."sandbox".environment]
  CURRENT_NETWORK = "sandbox"

# Livenet
[context."livenet".environment]
  CURRENT_NETWORK = "livenet"

# Livenet
[context."master".environment]
  CURRENT_NETWORK = "livenet"

# To remove when Livenet will be live
[[redirects]]
  from = "https://explorer.uns.network/*"
  to = "https://devnet.explorer.uns.network/"
  status = 302
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
