[build]
  publish = "dist/"
  command = "yarn build:dalinet --verbose"

[context."develop"]
# Nothing today

[context."devnet"]
  command = "yarn build:devnet --verbose"

[context."sandbox"]
# Nothing today

# Livenet
[context."master"]

# To remove when Livenet will be live
[[redirects]]
  from = "https://explorer.uns.network/*"
  to = "https://devnet.explorer.uns.network/"
  status = 302
  force = true
