<template>
  <section class="page-section py-5 md:py-10 mb-5">
    <div class="px-5 sm:px-10">
      <div class="list-row-border-b">
        <div>{{ $t("Transactions") }}</div>
        <div>{{ block.numberOfTransactions }}</div>
      </div>

      <div class="list-row-border-b">
        <div>{{ $t("Confirmations") }}</div>
        <div>{{ block.confirmations }}</div>
      </div>

      <div class="list-row-border-b">
        <div>{{ $t("Height") }}</div>
        <div>{{ block.height }}</div>
      </div>

      <div class="list-row-border-b">
        <div>{{ $t("Reward") }}</div>
        <div>{{ readableCrypto(block.reward) }}</div>
      </div>

      <div class="list-row-border-b">
        <div>{{ $t("Total Fee") }}</div>
        <div>{{ readableCrypto(block.totalFee) }}</div>
      </div>

      <div class="list-row-border-b">
        <div>{{ $t("Total Forged") }}</div>
        <div>{{ readableCrypto(block.totalForged) }}</div>
      </div>

      <div class="list-row-border-b">
        <div>{{ $t("Total Amount") }}</div>
        <div>{{ readableCrypto(block.totalAmount) }}</div>
      </div>

      <div class="list-row-border-b">
        <div>{{ $t("Timestamp") }}</div>
        <div>{{ readableTimestamp(block.timestamp) }}</div>
      </div>

      <div class="list-row">
        <div>{{ $t("Generated by") }}</div>
        <link-wallet :public-key="block.generatorPublicKey"></link-wallet>
      </div>
    </div>
  </section>
</template>

<script type="text/ecmascript-6">
export default {
  props: {
    block: {
      type: Object,
      required: true
    }
  }
}
</script>
