<template>
  <section class="page-section py-5 md:py-10 mb-5">
    <div class="px-5 sm:px-10">
      <div class="list-row-border-b">
        <div>{{ $t("Transactions") }}</div>
        <div>{{ block.transactions }}</div>
      </div>

      <div class="list-row-border-b">
        <div>{{ $t("Confirmations") }}</div>
        <div>{{ getConfirmations() }}</div>
      </div>

      <div class="list-row-border-b">
        <div>{{ $t("Height") }}</div>
        <div>{{ block.height }}</div>
      </div>

      <template v-if="block.forged">
        <div class="list-row-border-b">
          <div>{{ $t("Reward") }}</div>
          <div>{{ readableCrypto(block.forged.reward) }}</div>
        </div>

        <div class="list-row-border-b">
          <div>{{ $t("Total fee") }}</div>
          <div>{{ readableCrypto(block.forged.fee) }}</div>
        </div>

        <div class="list-row-border-b">
          <div>{{ $t("Total forged") }}</div>
          <div>{{ readableCrypto(block.forged.total) }}</div>
        </div>

        <div class="list-row-border-b">
          <div>{{ $t("Total amount") }}</div>
          <div>{{ readableCrypto(block.forged.amount) }}</div>
        </div>
      </template>

      <div v-if="block.timestamp" class="list-row-border-b">
        <div>{{ $t("Timestamp") }}</div>
        <div>{{ readableTimestamp(block.timestamp.unix) }}</div>
      </div>

      <div v-if="block.generator" class="list-row">
        <div>{{ $t("Generated by") }}</div>
        <link-wallet :address="block.generator.address"></link-wallet>
      </div>
    </div>
  </section>
</template>

<script type="text/ecmascript-6">
import { mapGetters } from 'vuex'

export default {
  props: {
    block: {
      type: Object,
      required: true
    }
  },

  computed: {
    ...mapGetters('network', ['height']),
  },

  methods: {
    prepareComponent() {
      this.getConfirmations()

      this.$store.watch(state => state.network.height, value => this.getConfirmations())
    },

    getConfirmations() {
      return this.block.height ? this.height - this.block.height : ''
    }
  }
}
</script>
