<template>
  <section class="page-section py-5 md:py-10 mb-5">
    <div class="px-5 sm:px-10">
      <div class="list-row-border-b">
        <div>{{ $t("Transactions") }}</div>
        <div>{{ block.transactions }}</div>
      </div>

      <div class="list-row-border-b">
        <div>{{ $t("Confirmations") }}</div>
        <div v-if="confirmations >= 0">
          {{ confirmations }}
        </div>
      </div>

      <div class="list-row-border-b">
        <div>{{ $t("Height") }}</div>
        <div>{{ block.height }}</div>
      </div>

      <div class="list-row-border-b">
        <div>{{ $t("Reward") }}</div>
        <div
          v-if="block.forged"
          v-tooltip="{
            trigger: 'hover click',
            content: price ? readableCurrency(block.forged.reward, price) : '',
            placement: 'left'
          }"
        >
          {{ readableCrypto(block.forged.reward) }}
        </div>
      </div>

      <div class="list-row-border-b">
        <div>{{ $t("Total fee") }}</div>
        <div
          v-if="block.forged"
          v-tooltip="{
            trigger: 'hover click',
            content: price ? readableCurrency(block.forged.fee, price) : '',
            placement: 'left'
          }"
        >
          {{ readableCrypto(block.forged.fee) }}
        </div>
      </div>

      <div class="list-row-border-b">
        <div>{{ $t("Total forged") }}</div>
        <div
          v-if="block.forged"
          v-tooltip="{
            trigger: 'hover click',
            content: price ? readableCurrency(block.forged.total, price) : '',
            placement: 'left'
          }"
        >
          {{ readableCrypto(block.forged.total) }}
        </div>
      </div>

      <div class="list-row-border-b">
        <div>{{ $t("Total amount") }}</div>
        <div
          v-if="block.forged"
          v-tooltip="{
            trigger: 'hover click',
            content: price ? readableCurrency(block.forged.amount, price) : '',
            placement: 'left'
          }"
        >
          {{ readableCrypto(block.forged.amount) }}
        </div>
      </div>

      <div class="list-row-border-b">
        <div>{{ $t("Timestamp") }}</div>
        <div v-if="block.timestamp">
          {{ readableTimestamp(block.timestamp.unix) }}
        </div>
      </div>

      <div class="list-row">
        <div>{{ $t("Generated by") }}</div>
        <div v-if="block.generator">
          <link-wallet :address="block.generator.address" />
        </div>
      </div>
    </div>
  </section>
</template>

<script type="text/ecmascript-6">
import CryptoCompareService from '@/services/crypto-compare'
import { mapGetters } from 'vuex'

export default {

  props: {
    block: {
      type: Object,
      required: true
    }
  },
  data: () => ({
    price: 0
  }),

  computed: {
    ...mapGetters('currency', { currencySymbol: 'symbol' }),
    ...mapGetters('network', ['height']),

    confirmations () {
      return this.height - this.block.height
    }
  },

  watch: {
    block () {
      this.updatePrice()
    },

    currencySymbol () {
      this.updatePrice()
    }
  },

  methods: {
    async updatePrice () {
      if (!this.block.id) {
        return
      }

      this.price = await CryptoCompareService.dailyAverage(this.block.timestamp.unix)
    }
  }
}
</script>
