// Currency.js
export const SET_CURRENCY_NAME: string = "SET_CURRENCY_NAME";
export const SET_CURRENCY_RATE: string = "SET_CURRENCY_RATE";
export const SET_CURRENCY_SYMBOL: string = "SET_CURRENCY_SYMBOL";
export const SET_CURRENCY_LAST_CONVERSION: string = "SET_CURRENCY_LAST_CONVERSION";

// UI.js
export const SET_UI_LANGUAGE: string = "SET_UI_LANGUAGE";
export const SET_UI_LOCALE: string = "SET_UI_LOCALE";
export const SET_UI_NIGHT_MODE: string = "SET_UI_NIGHT_MODE";
export const SET_UI_HEADER_TYPE: string = "SET_UI_HEADER_TYPE";
export const SET_UI_MENU_VISIBLE: string = "SET_UI_MENU_VISIBLE";
export const SET_UI_HAS_ACCEPTED_LINK_DISCLAIMER: string = "SET_UI_HAS_ACCEPTED_LINK_DISCLAIMER";
export const SET_UI_PRICE_CHART_OPTIONS: string = "SET_UI_PRICE_CHART_OPTIONS";
export const SET_UI_BLOCK_SORT_PARAMS: string = "SET_UI_BLOCK_SORT_PARAMS";
export const SET_UI_BUSINESS_SORT_PARAMS: string = "SET_UI_BUSINESS_SORT_PARAMS";
export const SET_UI_BRIDGECHAIN_SORT_PARAMS: string = "SET_UI_BRIDGECHAIN_SORT_PARAMS";
export const SET_UI_DELEGATE_SORT_PARAMS: string = "SET_UI_DELEGATE_SORT_PARAMS";
export const SET_UI_TRANSACTION_SORT_PARAMS: string = "SET_UI_TRANSACTION_SORT_PARAMS";
export const SET_UI_WALLET_SORT_PARAMS: string = "SET_UI_WALLET_SORT_PARAMS";
export const SET_UI_WALLET_TRANSACTION_TAB: string = "SET_UI_WALLET_TRANSACTION_TAB";

// Delegates.js
export const SET_DELEGATES: string = "SET_DELEGATES";
export const SET_FORGED: string = "SET_FORGED";

// Network.js
export const SET_NETWORK_DEFAULTS: string = "SET_NETWORK_DEFAULTS";
export const SET_NETWORK_SERVER: string = "SET_NETWORK_SERVER";
export const SET_NETWORK_TOKEN: string = "SET_NETWORK_TOKEN";
export const SET_NETWORK_SYMBOL: string = "SET_NETWORK_SYMBOL";
export const SET_NETWORK_NETHASH: string = "SET_NETWORK_NETHASH";
export const SET_NETWORK_CURRENCIES: string = "SET_NETWORK_CURRENCIES";
export const SET_NETWORK_KNOWN_WALLETS: string = "SET_NETWORK_KNOWN_WALLETS";
export const SET_NETWORK_SUPPLY: string = "SET_NETWORK_SUPPLY";
export const SET_NETWORK_UNIK_SUPPLY: string = "SET_NETWORK_UNIK_SUPPLY";
export const SET_NETWORK_HEIGHT: string = "SET_NETWORK_HEIGHT";
export const SET_NETWORK_EPOCH: string = "SET_NETWORK_EPOCH";
export const SET_NETWORK_BLOCKTIME: string = "SET_NETWORK_BLOCKTIME";
export const SET_NETWORK_ALIAS: string = "SET_NETWORK_ALIAS";
export const SET_NETWORK_ACTIVE_DELEGATES: string = "SET_NETWORK_ACTIVE_DELEGATES";
export const SET_NETWORK_REWARD_OFFSET: string = "SET_NETWORK_REWARD_OFFSET";
export const SET_NETWORK_ADDRESS_PREFIX: string = "SET_NETWORK_ADDRESS_PREFIX";
