<template>
  <loader :data="blocks">
    <table-component
      v-if="blocks && blocks.length"
      :data="blocks"
      sort-by="height"
      sort-order="desc"
      :show-filter="false"
      :show-caption="false"
      table-class="w-full"
    >
      <table-column
        show="id"
        :label="$t('ID')"
        header-class="left-header-start-cell"
        cell-class="left-start-cell"
      >
        <template slot-scope="row">
          <link-block :id="row.id" />
        </template>
      </table-column>

      <table-column
        show="height"
        :label="$t('Height')"
        header-class="left-header-cell hidden md:table-cell"
        cell-class="left-cell hidden md:table-cell"
      >
        <template slot-scope="row">
          {{ row.height }}
        </template>
      </table-column>

      <table-column
        show="timestamp.unix"
        :label="$t('Timestamp')"
        header-class="left-header-cell"
        cell-class="left-cell wrap-timestamp"
      >
        <template slot-scope="row">
          {{ readableTimestamp(row.timestamp.unix) }}
        </template>
      </table-column>

      <table-column
        show="transactions"
        :label="$t('Transactions')"
        header-class="right-header-cell hidden md:table-cell"
        cell-class="right-header-cell hidden md:table-cell border-none"
      >
        <template slot-scope="row">
          {{ row.transactions }}
        </template>
      </table-column>

      <table-column
        show="generator.username"
        :label="$t('Generated by')"
        header-class="right-header-cell hidden lg:table-cell"
        cell-class="right-cell hidden lg:table-cell"
      >
        <template slot-scope="row">
          <link-wallet :address="row.generator.address" />
        </template>
      </table-column>

      <table-column
        show="forged.total"
        :label="$t('Reward (token)', { token: networkToken() })"
        header-class="right-header-cell"
        cell-class="right-cell"
      >
        <template slot-scope="row">
          <span
            class="whitespace-no-wrap"
            v-tooltip="{
              trigger: 'hover',
              content: readableCurrency(row.forged.total, row.price)
            }"
          >
            {{ readableCrypto(row.forged.total) }}
          </span>
        </template>
      </table-column>

      <table-column
        show="forged.fee"
        :label="$t('Fee (token)', { token: networkToken() })"
        header-class="right-header-end-cell"
        cell-class="right-end-cell"
      >
        <template slot-scope="row">
          <span
            class="whitespace-no-wrap"
            v-tooltip="{
              trigger: 'hover',
              content: row.forged.fee ? readableCurrency(row.forged.fee, row.price) : ''
            }"
          >
            {{ readableCrypto(row.forged.fee) }}
          </span>
        </template>
      </table-column>
    </table-component>

    <div v-else class="px-5 md:px-10">
      <span>{{ $t("No results") }}</span>
    </div>
  </loader>
</template>

<script type="text/ecmascript-6">
import CryptoCompareService from '@/services/crypto-compare'

export default {
  props: {
    blocks: {
      // type: Array, or null
      required: true
    },
  },

  created() {
    if (!this.updatedBlocks) {
      this.updateBlocks()
    }
  },

  watch: {
    async blocks() {
      this.updateBlocks()
    }
  },

  methods: {
    async updateBlocks() {
      if (!this.blocks) {
        return
      }

      for (const block of this.blocks) {
        block.price = await CryptoCompareService.dailyAverage(block.timestamp.unix)
      }
    }
  }
}
</script>

<style>
  .wrap-timestamp {
    white-space: normal;
  }

  @media(min-width: 870px) {
    .wrap-timestamp {
      white-space: nowrap;
    }
  }
</style>
