<template>
  <table class="w-full">
    <thead>
      <tr class="opacity-25 text-xs">
        <th class="p-4 pl-10 text-left">ID</th>
        <th class="p-4 text-left hidden md:table-cell">Height</th>
        <th class="p-4 text-left">Timestamp</th>
        <th class="p-4 text-right hidden md:table-cell">Transactions</th>
        <th class="p-4 text-right hidden lg:table-cell">Generated by</th>
        <th class="p-4 text-right">Reward (ARK)</th>
        <th class="p-4 pr-10 text-right">Fee (ARK)</th>
      </tr>
    </thead>
    <tbody>
      <tr v-for="block in blocks" :key="block.id">
        <td class="p-4 pl-10 text-left border-none">
          <block-link :id="block.id"></block-link>
        </td>

        <td class="p-4 text-left border-none hidden md:table-cell">
          {{ block.height }}
        </td>

        <td class="p-4 text-left border-none">
          {{ readableTimestamp(block.timestamp) }}
        </td>

        <td class="p-4 text-right hidden md:table-cell border-none">
          {{ block.numberOfTransactions }}
        </td>

        <td class="p-4 text-right border-none hidden lg:table-cell">
          <wallet-link :public-key="block.generatorPublicKey"></wallet-link>
        </td>

        <td class="p-4 text-right border-none">
          {{ readableCrypto(block.totalForged) }}
        </td>

        <td class="p-4 pr-10 text-right border-none">
          {{ readableCrypto(block.totalFee) }}
        </td>
      </tr>
    </tbody>
  </table>
</template>

<script type="text/ecmascript-6">
import Currency from '@/components/utils/Currency'
import WalletLink from '@/components/links/Wallet'
import BlockLink from '@/components/links/Block'

export default {
  components: {
    Currency,
    BlockLink,
    WalletLink,
  },

  props: {
    blocks: {
      type: Array,
      required: true,
    },
  },
}
</script>

<style scoped>
tbody tr:nth-child(even) {
  background-color: var(--color-theme-table-row);
}

tbody tr:hover {
  background-color: rgba(0, 0, 0, 0);
  transform: scale(1.015);
  box-shadow: var(--theme-table-hover-shadow);
  z-index: 999;
  border-radius: 7px;
}
tr:hover,
tr:hover td {
  background-color: var(--color-theme-table-row-hover);
}
tr:hover td:first-child {
  border-top-left-radius: 7px;
  border-bottom-left-radius: 7px;
}
tr:hover td:last-child {
  border-top-right-radius: 7px;
  border-bottom-right-radius: 7px;
}
</style>
