version: 2
jobs:
  test-node-9:
    working_directory: ~/explorer
    docker:
      - image: circleci/node:9-browsers
    steps: &teststeps
      - checkout
      - run: mkdir test-reports
      - run:
          name: Download Selenium
          command: curl -O https://selenium-release.storage.googleapis.com/3.141/selenium-server-standalone-3.141.59.jar
      - run:
          name: Start Selenium
          command: java -jar selenium-server-standalone-3.141.59.jar -log test-reports/selenium.log
          background: true
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: Install
          command: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - run:
          name: Lint
          command: npm run lint
      - run:
          name: Unit tests
          command: npm run unit
      - run:
          name: Codecov
          when: on_success
          command: bash <(curl -s https://codecov.io/bash)
      - run:
          name: e2e tests
          command: npm run e2e
          environment:
            WITHOUT_SELENIUM_SERVER: true
      - run:
          name: Build
          command: npm run build
      - store_artifacts:
          path: test-reports/
          destination: test-results
      - store_test_results:
          path: test-reports/
      
  test-node-stable:
    working_directory: ~/explorer
    docker:
      - image: circleci/node:latest-browsers
    steps: *teststeps

workflows:
  version: 2
  test:
    jobs:
      - test-node-9
      - test-node-stable
