version: 2
jobs:
  test-node-11:
    working_directory: ~/explorer
    docker:
      - image: cypress/base:11.13.0
        environment:
          TERM: xterm
    steps: &teststeps
      - checkout
      - run: mkdir test-reports
      - restore_cache:
          key: dependency-cache-{{ checksum "yarn.lock" }}
      - run:
          name: Install
          command: yarn install
      - save_cache:
          key: dependency-cache-{{ checksum "yarn.lock" }}
          paths:
            - ./node_modules
            - ~/.cache
      - run:
          name: Lint
          command: yarn lint
      - run:
          name: Unit tests
          command: yarn test:unit
      - run:
          name: Codecov
          when: on_success
          command: bash <(curl -s https://codecov.io/bash)
      - run:
          name: e2e tests
          command: yarn test:e2e:ci
      - run:
          name: Build
          command: yarn build
      - store_test_results:
          path: test-reports/
      - store_artifacts:
          path: __tests__/e2e/videos
      - store_artifacts:
          path: __tests__/e2e/screenshots
  test-node-12:
    working_directory: ~/explorer
    docker:
      - image: cypress/base:12.6.0
        environment:
          TERM: xterm
    steps: *teststeps
workflows:
  version: 2
  test:
    jobs:
      - test-node-11
      - test-node-12
