<template>
  <div>
    <div v-for="block in blocks" :key="block.id" class="row-mobile">
      <div class="list-row-border-b">
        <div>ID</div>
        <link-block :id="block.id"></link-block>
      </div>

      <div class="list-row-border-b">
        <div>Height</div>
        <div>{{ block.height }}</div>
      </div>

      <div class="list-row-border-b">
        <div>Timestamp</div>
        <div>{{ readableTimestamp(block.timestamp) }}</div>
      </div>

      <div class="list-row-border-b">
        <div>Transactions</div>
        <div>{{ block.numberOfTransactions }}</div>
      </div>

      <div class="list-row-border-b">
        <div>Generated by</div>
        <link-wallet :public-key="block.generatorPublicKey"></link-wallet>
      </div>

      <div class="list-row-border-b">
        <div>Amount (ARK)</div>
        <div>{{ readableCrypto(block.totalForged) }}</div>
      </div>

      <div class="list-row">
        <div>Fee (ARK)</div>
        <div>{{ readableCrypto(block.totalFee) }}</div>
      </div>
    </div>
  </div>
</template>

<script type="text/ecmascript-6">
export default {
  props: {
    blocks: {
      type: Array,
      required: true,
    }
  }
}
</script>

<style scoped>
.row-mobile:nth-child(even) {
  background-color: var(--color-theme-table-row);
}
</style>
