// For authoring Nightwatch tests, see
// http://nightwatchjs.org/guide#usage

// Disable eslint for .to.not.be.present statements
/* eslint-disable no-unused-expressions */

module.exports = {
  // Default test, which also serves as setup for correct url
  'block page should be available': function (browser) {
    const devServer = browser.globals.devServerURL + '/#/blocks/1'

    browser
      .url(devServer)
      .waitForElementVisible('main.theme-light')
      .useXpath()
      .waitForElementVisible("//h1[text() = 'Blocks']")
  },

  'it should show 25 blocks in the table': function (browser) {
    browser
      .useCss()
      .waitForElementVisible('div.hidden.sm\\:block table.vgt-table tbody')
      .expect.element('div.hidden.sm\\:block').to.be.present
    browser
      .elements('css selector', 'div.hidden.sm\\:block table.vgt-table tbody tr', function (result) {
        browser.assert.equal(25, result.value.length)
      })
  },

  'it should be possible to sort the table': function (browser) {
    browser
      .useXpath().expect.element("//th[contains(., 'ID')]").to.be.present
    browser
      .assert.cssClassNotPresent("//th[contains(., 'ID')]", 'sorting-asc')
      .assert.cssClassNotPresent("//th[contains(., 'ID')]", 'sorting-desc')
    browser
      .click("//th[contains(., 'ID')]")
      .pause(500)
    browser.assert.cssClassPresent("//th[contains(., 'ID')]", 'sorting-asc')
    browser
      .click("//th[contains(., 'ID')]")
      .pause(500)
    browser.assert.cssClassPresent("//th[contains(., 'ID')]", 'sorting-desc')
  },

  'it should be possible to navigate to the next page and back': function (browser) {
    browser
      .assert.urlContains('/blocks/1')
      .useXpath().expect.element("//button[contains(., 'Previous')]").to.not.be.visible
    browser
      .expect.element("//button[contains(., 'Next')]").to.be.visible
    browser
      .click("//button[contains(., 'Next')]")
      .pause(500)
      .useCss().waitForElementVisible('table.vgt-table')
    browser
      .assert.urlContains('/blocks/2')
      .useXpath().click("//button[contains(., 'Previous')]")
      .pause(500)
      .useCss().waitForElementVisible('table.vgt-table')
    browser
      .assert.urlContains('/blocks/1')
  },

  'it should be possible to click on the block id': function (browser) {
    browser
      .useXpath()
      .waitForElementVisible('//tbody//tr[1]//td[1]//a[1]')
      .click('//tbody//tr[1]//td[1]//a[1]')
      .pause(500)
    browser
      .waitForElementVisible("//h1[text() = 'Block']")
    browser
      .assert.urlContains('/block/')
  },

  'it should be possible to click on generated by': function (browser) {
    const devServer = browser.globals.devServerURL + '/#/blocks/1'

    browser
      .url(devServer)
      .useCss()
      .waitForElementVisible('table.vgt-table', 10000)
      .useXpath()
      .waitForElementVisible('//tbody//tr[1]//td[5]//a[1]')
      .click('//tbody//tr[1]//td[5]//a[1]')
    browser
      .waitForElementVisible("//h1[text() = 'Wallet summary']")
      .assert.urlContains('/wallets/')
    browser.end()
  }
}
