// For authoring Nightwatch tests, see
// http://nightwatchjs.org/guide#usage

// Disable eslint for .to.not.be.present statements
/* eslint-disable no-unused-expressions */

module.exports = {
  // Default test, which also serves as setup for correct url
  'block page should be available': function (browserName) {
    const devServer = browserName.globals.devServerURL + '/#/blocks/1'

    browserName
      .url(devServer)
      .waitForElementVisible('main.theme-light')
      .useXpath()
      .waitForElementVisible("//h1[text() = 'Blocks']")
  },

  'it should show 25 blocks in the table': function (browserName) {
    browserName
      .useCss()
      .waitForElementVisible('div.hidden.sm\\:block div.table-component tbody.table-component__table__body')
      .expect.element('div.hidden.sm\\:block').to.be.present
    browserName
      .elements('css selector', 'div.hidden.sm\\:block div.table-component tbody.table-component__table__body tr', function (result) {
        browserName.assert.equal(25, result.value.length)
      })
  },

  'it should be possible to sort the table': function (browserName) {
    browserName
      .useXpath().expect.element("//th[contains(., 'ID')]").to.be.present
    browserName
      .assert.cssClassPresent("//th[contains(., 'ID')]", 'table-component__th--sort')
      .assert.cssClassNotPresent("//th[contains(., 'ID')]", 'table-component__th--sort-asc')
      .assert.cssClassNotPresent("//th[contains(., 'ID')]", 'table-component__th--sort-desc')
    browserName
      .click("//th[contains(., 'ID')]")
      .pause(500)
    browserName.assert.cssClassPresent("//th[contains(., 'ID')]", 'table-component__th--sort-asc')
    browserName
      .click("//th[contains(., 'ID')]")
      .pause(500)
    browserName.assert.cssClassPresent("//th[contains(., 'ID')]", 'table-component__th--sort-desc')
  },

  'it should be possible to navigate to the next page and back': function (browserName) {
    browserName
      .assert.urlContains('/blocks/1')
      .useXpath().expect.element("//button[contains(., 'Previous')]").to.not.be.visible
    browserName
      .expect.element("//button[contains(., 'Next')]").to.be.visible
    browserName
      .click("//button[contains(., 'Next')]")
      .pause(500)
      .useCss().waitForElementVisible('div.table-component')
    browserName
      .assert.urlContains('/blocks/2')
      .useXpath().click("//button[contains(., 'Previous')]")
      .pause(500)
      .useCss().waitForElementVisible('div.table-component')
    browserName
      .assert.urlContains('/blocks/1')
  },

  'it should be possible to click on the block id': function (browserName) {
    browserName
      .useXpath()
      .waitForElementVisible("//tbody[contains(@class, 'table-component__table__body')]//tr[1]//td[1]//a[1]")
      .click("//tbody[contains(@class, 'table-component__table__body')]//tr[1]//td[1]//a[1]")
      .pause(500)
    browserName
      .waitForElementVisible("//h1[text() = 'Block']")
    browserName
      .assert.urlContains('/block/')
  },

  'it should be possible to click on generated by': function (browserName) {
    const devServer = browserName.globals.devServerURL + '/#/blocks/1'

    browserName
      .url(devServer)
      .useCss()
      .waitForElementVisible('div.table-component', 10000)
      .useXpath()
      .waitForElementVisible("//tbody[contains(@class, 'table-component__table__body')]//tr[1]//td[5]//a[1]")
      .click("//tbody[contains(@class, 'table-component__table__body')]//tr[1]//td[5]//a[1]")
    browserName
      .waitForElementVisible("//h1[text() = 'Wallet summary']")
      .assert.urlContains('/wallets/')
    browserName.end()
  }
}
