name: Format

on:
    push:
        branches:
            - "master"
            - "develop"
    pull_request:
        types: [ready_for_review, synchronize, opened]

jobs:
    eslint:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2
              with:
                ref: ${{ github.head_ref }}

            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v1
              with:
                node-version: ${{ matrix.node-version }}

            - name: Install
              run: yarn install --frozen-lockfile

            - name: Run eslint
              run: yarn lint

            - uses: stefanzweifel/git-auto-commit-action@v2.5.0
              with:
                commit_message: "style: resolve style guide violations"
                commit_options: "--no-verify"
                branch: ${{ github.head_ref }}
              env:
                GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
