name: Format

on:
  pull_request:
    types: [ready_for_review, synchronize, opened]

jobs:
  eslint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}
          token: ${{ secrets.GH_TOKEN }}

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install
        run: yarn install --immutable --immutable-cache

      - name: Run eslint
        run: yarn lint

      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "style: resolve style guide violations"

  rustywind:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}
          token: ${{ secrets.GH_TOKEN }}

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Format
        run: |
          curl https://avencera.github.io/rustywind/install.sh --output install.sh
          sudo bash install.sh --git avencera/rustywind
          $(which rustywind) --write src
          rm install.sh

      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "style: resolve style guide violations"
          branch: ${{ github.head_ref }}
